version: 2.1
commands:
    runtests:
        parameters:
            toxcommand:
                type: string
                default: tox
        steps:
            - checkout

            - run:
                name: install tox
                command: >
                    python3.10 -m pip install --upgrade --force-reinstall tox pip

            - run:
                name: version checks
                command: |
                    python3.10 --version
                    tox --version

            - run:
                name: run tox
                command: << parameters.toxcommand >>

            - store_test_results:
                path: .circleci/test-reports/

            - run:
                name: push code coverage
                command: bash <(curl -s https://codecov.io/bash) -X coveragepy -t "1c18e756-0bd0-4106-98be-b2fedf1f88df"

jobs:
    postgres:
        docker:
            - image: level12/python-test-multi
              environment:
                SQLALCHEMY_DATABASE_URI: "postgresql://postgres@localhost:54321/postgres"
            - image: postgres:latest
              environment:
                POSTGRES_USER: postgres
                # Ok for local dev, potentially UNSAFE in other applications.  Don't blindly copy & paste
                # without considering implications.
                POSTGRES_HOST_AUTH_METHOD: trust
                POSTGRES_DB: postgres
                PGPORT: 54321
        steps:
            - runtests
    sqlite:
        docker:
            - image: level12/python-test-multi
              environment:
                  SQLALCHEMY_DATABASE_URI: "sqlite://"
        steps:
            - runtests
    mssql:
        docker:
            - image: level12/python-test-multi
              environment:
                  SQLALCHEMY_DATABASE_URI: "mssql+pyodbc_mssql://SA:Password12!@localhost:14331/tempdb?driver=ODBC+Driver+17+for+SQL+Server"
            - image: mcr.microsoft.com/mssql/server
              environment:
                ACCEPT_EULA: Y
                MSSQL_SA_PASSWORD: "Password12!"
                MSSQL_TCP_PORT: 14331
        steps:
            - runtests

workflows:
    version: 2
    build:
        jobs:
            - postgres
            - sqlite
            - mssql
