version: 2

jobs:
  postgres:
    docker:
      - image: level12/python-test-multi
        environment:
          SQLALCHEMY_DATABASE_URI: "postgresql://postgres:password@localhost/test"
      - image: postgres:10.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
    steps:
      - checkout

      - run:
          name: install tox and upgrade pip
          command: pip install --progress-bar off -U pip tox

      - run:
          name: version checks
          command: |
            python --version
            pip --version
            virtualenv --version
            tox --version

      - run:
          name: run tox
          command: tox

      - run:
          name: upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -t  1c18e756-0bd0-4106-98be-b2fedf1f88df
  sqlite:
    docker:
      - image: level12/python-test-multi
        environment:
          SQLALCHEMY_DATABASE_URI: "sqlite://"
    steps:
      - checkout

      - run:
          name: install tox and upgrade pip
          command: pip install --progress-bar off -U pip tox

      - run:
          name: version checks
          command: |
            python --version
            pip --version
            virtualenv --version
            tox --version

      - run:
          name: run tox
          command: tox

      - run:
          name: upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -t  1c18e756-0bd0-4106-98be-b2fedf1f88df
  mssql:
    docker:
      - image: level12/python-test-multi
        environment:
          SQLALCHEMY_DATABASE_URI: "mssql+pymssql://SA:Password12!@localhost:1433/tempdb"
      - image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: "Password12!"
    steps:
      - checkout

      - run:
          name: install tox and upgrade pip
          command: pip install --progress-bar off -U pip tox

      - run:
          name: version checks
          command: |
            python --version
            pip --version
            virtualenv --version
            tox --version

      - run:
          name: run tox
          command: tox -e py36-base,py37-base,py36-i18n,py37-i18n

      - run:
          name: upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -t  1c18e756-0bd0-4106-98be-b2fedf1f88df

workflows:
    version: 2
    build:
        jobs:
            - postgres
            - sqlite
            - mssql
